export const CLERK_PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY || 'pk_test_placeholder_key';
export const GOOGLE_MAPS_API_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY;
export const MELISSA_DATA_API_KEY = import.meta.env.VITE_MELISSA_DATA_API_KEY;
export const ROBOFLOW_API_KEY = import.meta.env.VITE_ROBOFLOW_API_KEY;
export const OPENROUTER_API_KEY = import.meta.env.VITE_OPENROUTER_API_KEY;
export const SITE_URL = import.meta.env.VITE_SITE_URL;
export const SITE_NAME = import.meta.env.VITE_SITE_NAME;
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;